version: '3.8'

services:
  backend:
    build: .
    container_name: metrics_backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: nginx:alpine
    container_name: metrics_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always
    depends_on:
      - backend